### ISSUE TITLE
Graph returned an Error (#200)

### ISSUE THREAD

**Issue by AlexanderProd** [Adau/facebook-rss-feed#1]
When loading index.php?page=GitHub I get the following error.

Graph returned an error: (#200) Access to this data is temporarily disabled for non-active apps or apps that have not recently accessed this data due to changes we are making to the Facebook Platform. https://developers.facebook.com/status/issues/205942813488872/

Even though I've created a Facebook app and set it to live. Do I have to do more to create a valid facebook app?

**Comment by Adau** [comment]
Hi Alexander,

No you don't have to do more, but Facebook is making changes in their APIs and during that process, they temporarily disable apps for a while. You can't do anything right now and have to wait.

Unless you have an app you created before March 2018.
